### ISSUE TITLE
[EPIC] Port gazebo-yarp-plugins functionality to Modern Gazebo

### ISSUE THREAD

**Issue by traversaro** [robotology/gz-yarp-plugins#17]
This issue is used to recap the "order" of the issue to solve:

* [x] FT: https://github.com/robotology/study-gazebo-garden-yarp-plugins/issues/4
* [x] robotinterface: https://github.com/robotology/study-gazebo-garden-yarp-plugins/issues/10
* [x] example with two FTs: https://github.com/robotology/study-gazebo-garden-yarp-plugins/issues/13
* [x] IMU: https://github.com/robotology/study-gazebo-garden-yarp-plugins/issues/14
* [x] laser: https://github.com/robotology/study-gazebo-garden-yarp-plugins/issues/16
* [x] camera: https://github.com/robotology/study-gazebo-garden-yarp-plugins/issues/15

**Comment by traversaro** [comment]
@lucapa17 @GiacomoBisio Given that the basic functionality has been solved, probably we can close this EPIC issue?
